/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PruebasRapidas;

import AlgortimoFuerzaBruta.Algoritmo;
import static Cartas.CrearMazo.CrearMazo;
import Cartas.MazoGeneral;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Prueba
     */
    public Vista() {
        initComponents();
        //  Posicionar ventana en el centro
        this.setLocationRelativeTo(null);
        //  Colocar Imagen en la aplicacion
        ImageIcon imagen = new ImageIcon(getClass().getResource("\\Imagen\\Pro1.png"));    //Direccion: "\\Imagen\\Pro1.png"
        Icon logo = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_SMOOTH));
        lblImagen.setIcon(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblRestricciones = new javax.swing.JLabel();
        spnRestricciones = new javax.swing.JSpinner();
        btnJugar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFuerzaBruta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taBackTracking = new javax.swing.JTextArea();
        lblTiempoBT = new javax.swing.JLabel();
        lblTiempoFB = new javax.swing.JLabel();
        txtTiempoBT = new javax.swing.JTextField();
        txtTiempoFB = new javax.swing.JTextField();
        lblSolucion = new javax.swing.JLabel();
        lblRestricciones2 = new javax.swing.JLabel();
        txtSolucion = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taRestricciones = new javax.swing.JTextArea();
        txtFB = new javax.swing.JTextField();
        lblBT = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("How it happened? 1.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 0, 0));
        lblTitulo.setText("How it happened?");

        lblRestricciones.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblRestricciones.setText("Ingrese el número de restricciones que desea que tenga los");

        spnRestricciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnJugar.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        taFuerzaBruta.setEditable(false);
        taFuerzaBruta.setColumns(20);
        taFuerzaBruta.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taFuerzaBruta.setRows(5);
        taFuerzaBruta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(taFuerzaBruta);

        taBackTracking.setEditable(false);
        taBackTracking.setColumns(20);
        taBackTracking.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        taBackTracking.setRows(5);
        taBackTracking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(taBackTracking);

        lblTiempoBT.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTiempoBT.setText("Tiempo en nanosegundos:");

        lblTiempoFB.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTiempoFB.setText("Tiempo en nanosegundos:");

        txtTiempoBT.setEditable(false);
        txtTiempoBT.setBackground(new java.awt.Color(0, 0, 0));
        txtTiempoBT.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        txtTiempoBT.setForeground(new java.awt.Color(102, 153, 0));
        txtTiempoBT.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTiempoFB.setEditable(false);
        txtTiempoFB.setBackground(new java.awt.Color(0, 0, 0));
        txtTiempoFB.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        txtTiempoFB.setForeground(new java.awt.Color(102, 153, 0));
        txtTiempoFB.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblSolucion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSolucion.setText("Solución:");

        lblRestricciones2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblRestricciones2.setText("Restricciones:");

        txtSolucion.setEditable(false);
        txtSolucion.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        txtSolucion.setForeground(new java.awt.Color(0, 0, 51));
        txtSolucion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolucionActionPerformed(evt);
            }
        });

        taRestricciones.setEditable(false);
        taRestricciones.setColumns(20);
        taRestricciones.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        taRestricciones.setRows(5);
        taRestricciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(taRestricciones);

        txtFB.setEditable(false);
        txtFB.setBackground(new java.awt.Color(0, 102, 204));
        txtFB.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtFB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFB.setText("Fuerza Bruta");
        txtFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFBActionPerformed(evt);
            }
        });

        lblBT.setEditable(false);
        lblBT.setBackground(new java.awt.Color(51, 153, 0));
        lblBT.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblBT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblBT.setText("Backtracking");
        lblBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("algoritmos jugadores:");

        javax.swing.GroupLayout pnlPanelLayout = new javax.swing.GroupLayout(pnlPanel);
        pnlPanel.setLayout(pnlPanelLayout);
        pnlPanelLayout.setHorizontalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelLayout.createSequentialGroup()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(161, 161, 161)
                                .addComponent(spnRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRestricciones)))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo)))
                .addGap(18, 18, 18)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSolucion)
                            .addComponent(lblRestricciones2))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBT, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblTiempoBT)
                                .addGap(47, 47, 47)
                                .addComponent(txtTiempoBT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblTiempoFB)
                                .addGap(50, 50, 50)
                                .addComponent(txtTiempoFB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFB, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPanelLayout.setVerticalGroup(
            pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelLayout.createSequentialGroup()
                                .addComponent(lblRestricciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnRestricciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSolucion)
                    .addComponent(txtSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblRestricciones2)))
                .addGap(18, 18, 18)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTiempoBT)
                        .addComponent(txtTiempoBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTiempoFB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTiempoFB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        
        //Llama y recibe datos del controlador
        String Ui = Controlador.iniciarJuego(spnRestricciones.getValue().toString());
        String[] UiParts = Ui.split(";");
        txtSolucion.setText(UiParts[0]);
        taRestricciones.setText(UiParts[1]);
        taFuerzaBruta.setText(UiParts[2]);
        txtTiempoFB.setText(UiParts[3]);

        
        //Coloca los datos directamente (SIN CONTROLADOR DE POR MEDIO)
        //en caso que los datos no salgan completos, usar este codigo:
//        MazoGeneral mazo = CrearMazo((Integer)spnRestricciones.getValue());     // Recibe el numero de restricciones. Se llevaría a cabo al presionar el boton JUGAR
//        Algoritmo prueba = new Algoritmo(mazo);                                 // Crea la clase que contiene el algoritmo. Recibe el mazo que debe trabajar
//        
//        String retrnFb = prueba.FuerzaBruta();      // Llama al de fuerza bruta
//        String[] retrnFbArray = retrnFb.split(";"); // Separar el dato del output y tiempo
//        String salidaFb = retrnFbArray[0];          // Output
//        String tiempoFb = retrnFbArray[1];          // Tiempo
//        taFuerzaBruta.setText(salidaFb);
//        txtTiempoFB.setText(tiempoFb);
//        
//        String strSolucion =                        //Esto obtiene la solucion
//                "Fue "+mazo.getSolucion().get(0)+
//                "con "+mazo.getSolucion().get(1)+
//                "por "+mazo.getSolucion().get(2)+
//                "en "+mazo.getSolucion().get(3)+
//                "dentro de "+mazo.getSolucion().get(4);
//        txtSolucion.setText(strSolucion);
//        
//        taRestricciones.setText(mazo.salidaRestricciones());

    }//GEN-LAST:event_btnJugarActionPerformed

    private void txtSolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolucionActionPerformed

    private void txtFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBActionPerformed

    private void lblBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lblBT;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblRestricciones;
    private javax.swing.JLabel lblRestricciones2;
    private javax.swing.JLabel lblSolucion;
    private javax.swing.JLabel lblTiempoBT;
    private javax.swing.JLabel lblTiempoFB;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlPanel;
    private javax.swing.JSpinner spnRestricciones;
    private javax.swing.JTextArea taBackTracking;
    private javax.swing.JTextArea taFuerzaBruta;
    private javax.swing.JTextArea taRestricciones;
    private javax.swing.JTextField txtFB;
    private javax.swing.JTextField txtSolucion;
    private javax.swing.JTextField txtTiempoBT;
    private javax.swing.JTextField txtTiempoFB;
    // End of variables declaration//GEN-END:variables
}
